code --install-extension aaron-bond.better-comments
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension jock.svg
code --install-extension Luxcium.pop-n-lock-theme-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension sainnhe.gruvbox-material
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension codingyu.laravel-goto-view
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-debug
code --install-extension jeremyrajan.webpack
code --install-extension KnisterPeter.vscode-commitizen
code --install-extension mikestead.dotenv
code --install-extension ms-vscode.csharp
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel-extension-pack
code --install-extension onecentlin.laravel5-snippets
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension ryannaddy.laravel-artisan
code --install-extension yzhang.markdown-all-in-one
code --install=extension MS-CEINTL.vscode-language-pack-ru

cp settings.json ~/AppData/Roaming/Code/User/settings.json
